### ISSUE TITLE
Duplicated Code

### ISSUE THREAD

**Issue by MatthewLundberg** [garybuhrmaster/HDHRUtil#1]
I see that many of these files contain a definition of the function HDHRdiscover.  This should be defined in one file only, and using import pulled, into other modules.

**Comment by garybuhrmaster** [comment]
While you are correct in (pythonic) principal, you are wrong in practice, as that would require installation of a group of files (typically using one of the python install programs) rather than just single file install (or even just copy) and go, and on some platforms, that is problematic, or above the competency of some of the user(s) that have used these standalone programs.  Having complete single file solutions allows for easier usage by the target audiences.  Perfect is the enemy of the good enough.
